WIP:

diff --git a/wifi-fun/docker-compose.yml b/wifi-fun/docker-compose.yml
--- a/wifi-fun/docker-compose.yml
+++ b/wifi-fun/docker-compose.yml
@@ -97,78 +97,55 @@ services:
       KSQL_BOOTSTRAP_SERVERS: kafka-1:39092,kafka-2:49092,kafka-3:59092
       KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
       KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
-      KSQL_KSQL_CONNECT_URL: http://kafka-connect-01:8083
       KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
-
-  # kafka-connect-01:
-  #   image: confluentinc/cp-kafka-connect:5.4.0
-  #   container_name: kafka-connect-01
-  #   depends_on:
-  #     - kafka-1
-  #     - kafka-2
-  #     - kafka-3
-  #     - schema-registry
-  #     - mysql
-  #   ports:
-  #     - 8083:8083
-  #   environment:
-  #     CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
-  #     CONNECT_CUB_KAFKA_TIMEOUT: 300
-  #     CONNECT_BOOTSTRAP_SERVERS: "kafka-1:39092,kafka-2:49092,kafka-3:59092"
-  #     CONNECT_REST_ADVERTISED_HOST_NAME: 'kafka-connect-01'
-  #     CONNECT_REST_PORT: 8083
-  #     CONNECT_GROUP_ID: kafka-connect-group-01
-  #     CONNECT_CONFIG_STORAGE_TOPIC: _kafka-connect-group-01-configs
-  #     CONNECT_OFFSET_STORAGE_TOPIC: _kafka-connect-group-01-offsets
-  #     CONNECT_STATUS_STORAGE_TOPIC: _kafka-connect-group-01-status
-  #     CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
-  #     CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
-  #     CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
-  #     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
-  #     CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
-  #     CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
-  #     CONNECT_LOG4J_ROOT_LOGLEVEL: 'INFO'
-  #     CONNECT_LOG4J_LOGGERS: 'org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR'
-  #     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
-  #     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
-  #     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
-  #     CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/,/data/connect-jars'
-  #     # External secrets config
-  #     # See https://docs.confluent.io/current/connect/security.html#externalizing-secrets
-  #     CONNECT_CONFIG_PROVIDERS: 'file'
-  #     CONNECT_CONFIG_PROVIDERS_FILE_CLASS: 'org.apache.kafka.common.config.provider.FileConfigProvider'
-  #   volumes:
-  #     - ./data:/data
-  #     - ${PWD}/.env:/data/credentials.properties
-  #   command: 
-  #     # In the command section, $ are replaced with $$ to avoid the error 'Invalid interpolation format for "command" option'
-  #     - bash 
-  #     - -c 
-  #     - |
-  #       echo "Installing connector plugins"
-  #       confluent-hub install --no-prompt confluentinc/kafka-connect-mqtt:1.2.3
-  #       confluent-hub install --no-prompt debezium/debezium-connector-mysql:0.10.0
-  #       #
-  #       echo "Launching Kafka Connect worker"
-  #       /etc/confluent/docker/run & 
-  #       #
-  #       echo "Waiting for Kafka Connect to start listening on $$CONNECT_REST_ADVERTISED_HOST_NAME:$$CONNECT_REST_PORT ⏳"
-  #       while : ; do
-  #         curl_status=$$(curl -s -o /dev/null -w %{http_code} http://$$CONNECT_REST_ADVERTISED_HOST_NAME:$$CONNECT_REST_PORT/connectors)
-  #         echo -e $$(date) " Kafka Connect listener HTTP state: " $$curl_status " (waiting for 200)"
-  #         if [ $$curl_status -eq 200 ] ; then
-  #           break
-  #         fi
-  #         sleep 5 
-  #       done
-  #       #
-  #       echo "Waiting for Schema Registry to start listening on schema-registry:8081 ⏳"
-  #       while [ $$(curl -s -o /dev/null -w %{http_code} http://schema-registry:8081) -eq 000 ] ; do 
-  #         echo -e $$(date) " Schema Registry listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://schema-registry:8081) " (waiting for != 000)"
-  #         sleep 5 
-  #       done
-  #       #      
-  #       sleep infinity
+      KSQL_STREAMS_PRODUCER_MAX_BLOCK_MS: 9223372036854775807
+      # Setting KSQL_KSQL_CONNECT_WORKER_CONFIG enables embedded Kafka Connect
+      #KSQL_KSQL_CONNECT_URL: http://kafka-connect-01:8083
+      KSQL_KSQL_CONNECT_WORKER_CONFIG: "/connect/connect.properties"
+      # Kafka Connect config below
+      KSQL_CONNECT_BOOTSTRAP_SERVERS: kafka-1:39092,kafka-2:49092,kafka-3:59092
+      KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: 'ksqldb'
+      KSQL_CONNECT_REST_PORT: 8083
+      KSQL_CONNECT_GROUP_ID: ksqldb-kafka-connect-group-01
+      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: _ksqldb-kafka-connect-group-01-configs
+      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: _ksqldb-kafka-connect-group-01-offsets
+      KSQL_CONNECT_STATUS_STORAGE_TOPIC: _ksqldb-kafka-connect-group-01-status
+      KSQL_CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
+      KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
+      KSQL_CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
+      KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
+      KSQL_CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
+      KSQL_CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/,/data/connect-jars'
+    # If you want to use the Confluent Hub installer to d/l component, but make them available
+    # when running this offline, spin up the stack once and then run : 
+    #   docker cp ksqldb:/usr/share/confluent-hub-components ./data/connect-jars
+    volumes:
+      - $PWD/data:/data
+    command: 
+      # In the command section, $ are replaced with $$ to avoid the error 'Invalid interpolation format for "command" option'
+      - bash 
+      - -c 
+      - |
+        # Manually install the Confluent Hub client
+        # This is ugly af but works
+        cd ~
+        rm confluent-hub-client-latest.tar.gz
+        wget http://client.hub.confluent.io/confluent-hub-client-latest.tar.gz
+        tar xf confluent-hub-client-latest.tar.gz
+        export PATH=$PATH:~/bin/
+        #
+        echo "Installing connector plugins"
+        mkdir -p /usr/share/confluent-hub-components/
+        confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components/ confluentinc/kafka-connect-elasticsearch:5.4.0
+        confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components/ confluentinc/kafka-connect-jdbc:5.4.0
+        confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components/ neo4j/kafka-connect-neo4j:1.0.2
+        confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components/ mdrogalis/voluble:0.1.0
+        confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components/ debezium/debezium-connector-mongodb:0.10.0
+        #
+        echo "Launching ksqlDB"
+        /usr/bin/docker/run & 
+        #
+        sleep infinity
 
   replicator:
     image: confluentinc/cp-enterprise-replicator:5.4.0
@@ -202,104 +179,92 @@ services:
       CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/'
       CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: 'All'
 
+  mongodb:
+    # *-----------------------------*
+    # To connect to mongoDB
+    #   docker exec --interactive --tty mongodb mongo localhost:27017
+    # *-----------------------------*
+    image: mongo:4.2.2
+    hostname: mongodb
+    ports: 
+    - "27017:27017"
+    command: 
+      - bash 
+      - -c 
+      - |
+        # Launch mongodb
+        mongod --replSet replSet01 --bind_ip_all &
+        # Wait for Mongo to be available 
+        # Based on https://stackoverflow.com/questions/16542372/shell-script-check-mongod-server-is-running
+        while : ; do
+          mongo_status=$$(mongo --eval "db.stats()" > /dev/null; echo $$?)
+          echo -e $$(date) " Mongo RC: " $$mongo_status " (waiting for 0)"
+          if [ $$mongo_status -eq 0 ] ; then
+            break
+          fi
+          sleep 5 
+        done
+        # Init the replicaset
+        mongo admin --eval "rs.initiate();"
+        sleep infinity
 
-  # elasticsearch:
-  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
-  #   container_name: elasticsearch
-  #   ports:
-  #     - 9200:9200
-  #   environment:
-  #     xpack.security.enabled: "false"
-  #     ES_JAVA_OPTS: "-Xms1g -Xmx1g"
-  #     discovery.type: "single-node"
-  #   # volumes: 
-  #   #   - ./data/container_data/elasticserarch:/usr/share/elasticsearch/data
-  #   command: 
-  #     - bash 
-  #     - -c 
-  #     - |
-  #       /usr/local/bin/docker-entrypoint.sh & 
-  #       echo "Waiting for Elasticsearch to start ⏳"
-  #       while [ $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) -eq 000 ] ; do 
-  #         echo -e $$(date) " Elasticsearch listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) " (waiting for != 000)"
-  #         sleep 5 
-  #       done
+  neo4j:
+    image: neo4j:3.5-enterprise
+    container_name: neo4j
+    hostname: neo4j
+    ports:
+    - "7474:7474"
+    - "7687:7687"
+    environment:
+      NEO4J_AUTH: neo4j/connect
+      NEO4J_dbms_memory_heap_max__size: 8G
+      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
 
-  #       curl -XPUT "http://localhost:9200/_template/kafkaconnect/" -H 'Content-Type: application/json' -d'
-  #         {
-  #           "index_patterns": "*",
-  #           "settings": { "number_of_shards": 1, "number_of_replicas": 0 },
-  #           "mappings": { "dynamic_templates": [
-  #               { "dates": { "match": "*_TS", "mapping": { "type": "date" } } },
-  #               { "heights": { "match": "HEIGHT", "mapping": { "type": "float" } } },
-  #               { "locations": { "match": "LOCATION", "mapping": { "type": "geo_point" } } }
-  #           ] } }'        
+  elasticsearch:
+    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
+    hostname: elasticsearch
+    # ports:
+    #   - 9200:9200
+    environment:
+      xpack.security.enabled: "false"
+      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
+      discovery.type: "single-node"
+    # volumes: 
+    #   - ./data/container_data/elasticserarch:/usr/share/elasticsearch/data
+    command: 
+      - bash 
+      - -c 
+      - |
+        /usr/local/bin/docker-entrypoint.sh & 
+        echo "Waiting for Elasticsearch to start ⏳"
+        while [ $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) -eq 000 ] ; do 
+          echo -e $$(date) " Elasticsearch listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) " (waiting for != 000)"
+          sleep 5 
+        done
 
-  #       sleep infinity
+        curl -XPUT "http://localhost:9200/_template/kafkaconnect/" -H 'Content-Type: application/json' -d'
+          {
+            "index_patterns": "*",
+            "settings": { "number_of_shards": 1, "number_of_replicas": 0 },
+            "mappings": { "dynamic_templates": [
+                { "dates1": { "match": "date", "mapping": { "type": "date" } } },
+                { "dates2": { "match": "DATE", "mapping": { "type": "date" } } },
+                { "dates3": { "match": "*_TS", "mapping": { "type": "date" } } }
+            ] } }'        
 
+        sleep infinity
 
-  # kibana:
-  #   image: docker.elastic.co/kibana/kibana:7.5.0
-  #   container_name: kibana
-  #   depends_on:
-  #     - elasticsearch
-  #   ports:
-  #     - 5601:5601
-  #   environment:
-  #     xpack.security.enabled: "false"
-  #     discovery.type: "single-node"
-  #   # command: 
-  #   #   - bash 
-  #   #   - -c 
-  #   #   - |
-  #   #     /usr/local/bin/kibana-docker & 
-  #   #     #
-  #   #     echo "Waiting for Kibana to start ⏳"
-  #   #     while : ; do
-  #   #       curl_status=$$(curl -s -o /dev/null -w %{http_code} http://localhost:5601/api/kibana/settings)
-  #   #       echo -e $$(date) " Kibana listener HTTP state: " $$curl_status " (waiting for 200)"
-  #   #       if [ $$curl_status -eq 200 ] ; then
-  #   #         break
-  #   #       fi
-  #   #       sleep 5 
-  #   #     done
-  #   #     #
-  #   #     echo "Waiting for Kibana API to be available ⏳"
-  #   #     while : ; do
-  #   #       kibana_status=$$(curl -s 'http://localhost:5601/api/kibana/settings')
-  #   #       echo -e $$(date) " Kibana API response: " $$kibana_status
-  #   #       if [ $$kibana_status != "Kibana server is not ready yet" ] ; then
-  #   #         break
-  #   #       fi
-  #   #       sleep 5 
-  #   #     done
-  #   #     #
-  #   #     sleep 60 
-  #   #     echo -e "\n--\n+> Setup Kibana objects"
+  kibana:
+    image: docker.elastic.co/kibana/kibana:7.5.0
+    hostname: kibana
+    depends_on:
+      - elasticsearch
+    ports:
+      - 5601:5601
+    environment:
+      xpack.security.enabled: "false"
+      discovery.type: "single-node"
 
-  #   #     echo -e "\n--\n+> Opt out of Kibana telemetry"
-  #   #     curl 'http://localhost:5601/api/telemetry/v1/optIn' -H 'kbn-xsrf: nevergonnagiveyouup' -H 'content-type: application/json' -H 'accept: application/json' --data-binary '{"enabled":false}' --compressed
-
-  #   #     echo -e "\n--\n+> Create Kibana index patterns"
-  #   #     curl -XPOST 'http://localhost:5601/api/saved_objects/index-pattern/runner_location_idx' \
-  #   #         -H 'kbn-xsrf: nevergonnagiveyouup' \
-  #   #         -H 'Content-Type: application/json' \
-  #   #         -d '{"attributes":{"title":"runner_location","timeFieldName":"EVENT_TS"}}'
-
-  #   #     curl -XPOST 'http://localhost:5601/api/saved_objects/index-pattern/runner_status_idx' \
-  #   #         -H 'kbn-xsrf: nevergonnagiveyouup' \
-  #   #         -H 'Content-Type: application/json' \
-  #   #         -d '{"attributes":{"title":"runner_status","timeFieldName":"EVENT_TS"}}'
-
-  #   #     echo -e "\n--\n+> Set default Kibana index"
-  #   #     curl -XPOST 'http://localhost:5601/api/kibana/settings' \
-  #   #         -H 'kbn-xsrf: nevergonnagiveyouup' \
-  #   #         -H 'content-type: application/json' \
-  #   #         -d '{"changes":{"defaultIndex":"runner_status_idx"}}'
-
-  #   #     echo -e "\n--\n+> Import Kibana objects"
-
-  #   #     sleep infinity
 
   # mysql:
   #   # *-----------------------------*
